[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/send-message"
  to = "/.netlify/functions/send-message"
  status = 200


[[redirects]]
  from = "/api/send-telegram"
  to = "/.netlify/functions/send-telegram"
  status = 200